apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spectrumknx-knxproj
  labels:
    app: spectrumknx-knxproj
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: "spectrumknx-knxproj"
