apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spectrumknx-timescale
  labels:
    app: spectrumknx-timescale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "spectrumknx-timescale"
